In [1]:
import numpy as np

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import regularizers
from sklearn.utils import shuffle


import matplotlib.pyplot as plt

In [2]:
#Test implementation of triplet loss function 
num_data = 10
feat_dim = 6
margin = 0.2

In [3]:
embeddings = [np.random.rand(num_data, feat_dim).astype(np.float32),
              np.random.rand(num_data, feat_dim).astype(np.float32),
              np.random.rand(num_data, feat_dim).astype(np.float32)]

In [5]:
embeddings

[array([[4.5181713e-01, 3.7829283e-01, 4.1921139e-01, 8.5711336e-01,
         2.1823148e-01, 5.3608175e-02],
        [7.0106494e-01, 6.1839100e-02, 9.3589365e-01, 1.7886186e-01,
         6.8123066e-01, 8.4771293e-01],
        [7.3391691e-02, 7.2488368e-01, 6.5082681e-01, 7.3388082e-01,
         9.2085075e-01, 4.8518210e-04],
        [3.0319110e-01, 3.9579037e-01, 2.0935582e-01, 1.1962967e-01,
         2.6045564e-01, 6.7503363e-01],
        [7.6030606e-01, 4.2399213e-01, 6.8845230e-01, 5.0208968e-01,
         9.4035737e-02, 1.1812676e-01],
        [5.8021528e-01, 5.7038903e-01, 5.4501975e-01, 8.0889553e-01,
         9.8018162e-03, 6.3672340e-01],
        [4.1470653e-01, 8.7032214e-02, 2.1712047e-01, 4.9986193e-01,
         3.7923777e-01, 5.3729934e-01],
        [7.7941215e-01, 5.0795031e-01, 5.1249033e-01, 4.5554299e-02,
         5.3430098e-01, 2.9619408e-01],
        [3.8935500e-01, 3.3888900e-01, 4.3527365e-01, 7.1951312e-01,
         8.3765024e-01, 8.2094687e-01],
        [9.8063660e

In [9]:
labels = np.random.randint(0, 1, size=(num_data)).astype(np.float32)
labels

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [17]:
loss_np = 0
anchor = embeddings[0]
positive = embeddings[1]
negative = embeddings[2]

In [18]:
for i in range(num_data):
    pos_dict = np.sum(np.square(anchor[i]-positive[i]))
    neg_dict = np.sum(np.square(anchor[i]-negative[i]))
    loss_np += max(pos_dict-neg_dict+margin, 0.)

loss_np

2.8234695315361025

In [19]:
loss_np /= num_data
loss_np

0.28234695315361025

In [20]:
print('Triplet loss computed with numpy', loss_np)

Triplet loss computed with numpy 0.28234695315361025


In [23]:
anchor = embeddings[0]
positive = embeddings[1]
negative = embeddings[2]

In [30]:
anchor

array([[4.5181713e-01, 3.7829283e-01, 4.1921139e-01, 8.5711336e-01,
        2.1823148e-01, 5.3608175e-02],
       [7.0106494e-01, 6.1839100e-02, 9.3589365e-01, 1.7886186e-01,
        6.8123066e-01, 8.4771293e-01],
       [7.3391691e-02, 7.2488368e-01, 6.5082681e-01, 7.3388082e-01,
        9.2085075e-01, 4.8518210e-04],
       [3.0319110e-01, 3.9579037e-01, 2.0935582e-01, 1.1962967e-01,
        2.6045564e-01, 6.7503363e-01],
       [7.6030606e-01, 4.2399213e-01, 6.8845230e-01, 5.0208968e-01,
        9.4035737e-02, 1.1812676e-01],
       [5.8021528e-01, 5.7038903e-01, 5.4501975e-01, 8.0889553e-01,
        9.8018162e-03, 6.3672340e-01],
       [4.1470653e-01, 8.7032214e-02, 2.1712047e-01, 4.9986193e-01,
        3.7923777e-01, 5.3729934e-01],
       [7.7941215e-01, 5.0795031e-01, 5.1249033e-01, 4.5554299e-02,
        5.3430098e-01, 2.9619408e-01],
       [3.8935500e-01, 3.3888900e-01, 4.3527365e-01, 7.1951312e-01,
        8.3765024e-01, 8.2094687e-01],
       [9.8063660e-01, 7.5210983e-01,

In [21]:
def triplet_loss(y_true, y_pred, margin=0.4):
    anchor = y_pred[0]
    positive = y_pred[1]
    negative = y_pred[2]
    
    pos_dist = tf.reduce_sum(tf.square(anchor-positive), axis=1)
    neg_dist = tf.reduce_sum(tf.square(anchor-negative), axis=1)
    
    # compute loss
    basic_loss = pos_dist-neg_dist+margin
    loss = tf.maximum(basic_loss,0.0)
    loss = tf.reduce_mean(loss)     
    return loss

In [35]:
a = np.array([[1.,2.,3.,4.], [10.,20.,30.,40.]])
b = np.array([[2.,3.,4.,5.], [20.,30.,40.,50.]])
a-b

array([[ -1.,  -1.,  -1.,  -1.],
       [-10., -10., -10., -10.]])

In [2]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
x_train.shape

(60000, 28, 28)

In [4]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [6]:
img_rows, img_cols = x_train.shape[1:3]
num_classes = len(np.unique(y_train))

# reshape the input arrays to 4D (batch_size, rows, columns, channels)
x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)
batch_size = 128
#for debugging use 3 epochs
#epochs = 3
epochs = 12

# convert to float32 and rescale between 0 and 1
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
